[package]
name = "auralist-rs"
version = "0.1.0"
authors = ["Elliott Landsborough <elliott@muzmatch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.16"
walkdir = "2"
flate2 = "1.0"
lazy_static = "1.4.0"

[dependencies.rusqlite]
version = "0.24.2"
default-features = false # don't include any defaults
features = ["backup"] # see rusqlite/blob/master/Cargo.toml
