[package]
name = "auralist-rs"
version = "0.1.0"
authors = ["Elliott Landsborough <elliott.landsborough@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A tool to search media files"
readme = "README.md"
homepage = "https://github.com/ElliottLandsborough/auralist-rs"
repository = "https://github.com/ElliottLandsborough/auralist-rs"
keywords = ["mp3", "indexer", "search"]
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.16"
walkdir = "2"
flate2 = "1.0"
id3 = "0.6.1"
taglib = "*"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
uuid = { version = "0.8", features = ["serde", "v4"] }
mime_guess = "2.0.3"
async-stream = "0.3.2"
hyper = "0.14.9"

#tree_magic = "0.2.3"

[dependencies.rusqlite]
version = "0.24.2"
default-features = false # don't include any defaults
features = ["backup"] # see rusqlite/blob/master/Cargo.toml
