[package]
name = "auralist-rs"
version = "0.1.0"
authors = ["Elliott Landsborough <elliott@muzmatch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.2"
walkdir = "2"