[package]
name = "auralist-rs"
version = "0.1.0"
authors = ["Elliott Landsborough <elliott.landsborough@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A tool to search media files"
readme = "README.md"
homepage = "https://github.com/ElliottLandsborough/auralist-rs"
repository = "https://github.com/ElliottLandsborough/auralist-rs"
keywords = ["mp3", "indexer", "search"]
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.16"
walkdir = "2"
flate2 = "1.0"
twox-hash = "1.6.0"
id3 = "0.6.1"
taglib = "*"

#tree_magic = "0.2.3"

[dependencies.rusqlite]
version = "0.24.2"
default-features = false # don't include any defaults
features = ["backup"] # see rusqlite/blob/master/Cargo.toml
